//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Solution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendees
    {
        public System.Guid UserId { get; set; }
        public System.Guid EventId { get; set; }
        public int AttendeeStatusId { get; set; }
    
        public virtual AttendeeStatus AttendeeStatus { get; set; }
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
