//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Solution
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HarkkaprojektiDBEntities2 : DbContext
    {
        public HarkkaprojektiDBEntities2()
            : base("name=HarkkaprojektiDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Attendees> Attendees { get; set; }
        public DbSet<AttendeeStatus> AttendeeStatus { get; set; }
        public DbSet<Event> Event { get; set; }
        public DbSet<EventType> EventType { get; set; }
        public DbSet<Group> Group { get; set; }
        public DbSet<GroupMembers> GroupMembers { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Testitaulu> Testitaulu { get; set; }
        public DbSet<User> User { get; set; }
    }
}
