//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Solution
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Attendees = new HashSet<Attendees>();
            this.GroupMembers = new HashSet<GroupMembers>();
        }
    
        public System.Guid UserID { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Attendees> Attendees { get; set; }
        public virtual ICollection<GroupMembers> GroupMembers { get; set; }
    }
}
