//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("HarkkaprojektiDBModel", "FK_KAYTTAJANTAPAHTUMAT_KAYTTAJAID", "Kayttaja", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Darkside.WCF4Silverlight.Model.Kayttaja), "KayttajanTapahtumat", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Darkside.WCF4Silverlight.Model.KayttajanTapahtumat))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("HarkkaprojektiDBModel", "FK_KAYTTAJANTAPAHTUMAT_TAPAHTUMAID", "Tapahtuma", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Darkside.WCF4Silverlight.Model.Tapahtuma), "KayttajanTapahtumat", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Darkside.WCF4Silverlight.Model.KayttajanTapahtumat))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("HarkkaprojektiDBModel", "FK_TAPAHTUMA_TYYPPIID", "Tapahtumatyyppi", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Darkside.WCF4Silverlight.Model.Tapahtumatyyppi), "Tapahtuma", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Darkside.WCF4Silverlight.Model.Tapahtuma))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("HarkkaprojektiDBModel", "RyhmanJasenet", "Kayttaja", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Darkside.WCF4Silverlight.Model.Kayttaja), "Ryhma", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Darkside.WCF4Silverlight.Model.Ryhma))]

// Original file name:
// Generation date: 8.5.2014 11:12:43
namespace Darkside.WCF4Silverlight.Model
{
    
    /// <summary>
    /// There are no comments for HarkkaprojektiDBEntities in the schema.
    /// </summary>
    public partial class HarkkaprojektiDBEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new HarkkaprojektiDBEntities object using the connection string found in the 'HarkkaprojektiDBEntities' section of the application configuration file.
        /// </summary>
        public HarkkaprojektiDBEntities() : 
                base("name=HarkkaprojektiDBEntities", "HarkkaprojektiDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new HarkkaprojektiDBEntities object.
        /// </summary>
        public HarkkaprojektiDBEntities(string connectionString) : 
                base(connectionString, "HarkkaprojektiDBEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new HarkkaprojektiDBEntities object.
        /// </summary>
        public HarkkaprojektiDBEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "HarkkaprojektiDBEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Kayttaja in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Kayttaja> Kayttaja
        {
            get
            {
                if ((this._Kayttaja == null))
                {
                    this._Kayttaja = base.CreateQuery<Kayttaja>("[Kayttaja]");
                }
                return this._Kayttaja;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Kayttaja> _Kayttaja;
        /// <summary>
        /// There are no comments for KayttajanTapahtumat in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<KayttajanTapahtumat> KayttajanTapahtumat
        {
            get
            {
                if ((this._KayttajanTapahtumat == null))
                {
                    this._KayttajanTapahtumat = base.CreateQuery<KayttajanTapahtumat>("[KayttajanTapahtumat]");
                }
                return this._KayttajanTapahtumat;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<KayttajanTapahtumat> _KayttajanTapahtumat;
        /// <summary>
        /// There are no comments for Ryhma in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Ryhma> Ryhma
        {
            get
            {
                if ((this._Ryhma == null))
                {
                    this._Ryhma = base.CreateQuery<Ryhma>("[Ryhma]");
                }
                return this._Ryhma;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Ryhma> _Ryhma;
        /// <summary>
        /// There are no comments for Tapahtuma in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Tapahtuma> Tapahtuma
        {
            get
            {
                if ((this._Tapahtuma == null))
                {
                    this._Tapahtuma = base.CreateQuery<Tapahtuma>("[Tapahtuma]");
                }
                return this._Tapahtuma;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Tapahtuma> _Tapahtuma;
        /// <summary>
        /// There are no comments for Tapahtumatyyppi in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Tapahtumatyyppi> Tapahtumatyyppi
        {
            get
            {
                if ((this._Tapahtumatyyppi == null))
                {
                    this._Tapahtumatyyppi = base.CreateQuery<Tapahtumatyyppi>("[Tapahtumatyyppi]");
                }
                return this._Tapahtumatyyppi;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Tapahtumatyyppi> _Tapahtumatyyppi;
        /// <summary>
        /// There are no comments for Kayttaja in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToKayttaja(Kayttaja kayttaja)
        {
            base.AddObject("Kayttaja", kayttaja);
        }
        /// <summary>
        /// There are no comments for KayttajanTapahtumat in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToKayttajanTapahtumat(KayttajanTapahtumat kayttajanTapahtumat)
        {
            base.AddObject("KayttajanTapahtumat", kayttajanTapahtumat);
        }
        /// <summary>
        /// There are no comments for Ryhma in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToRyhma(Ryhma ryhma)
        {
            base.AddObject("Ryhma", ryhma);
        }
        /// <summary>
        /// There are no comments for Tapahtuma in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToTapahtuma(Tapahtuma tapahtuma)
        {
            base.AddObject("Tapahtuma", tapahtuma);
        }
        /// <summary>
        /// There are no comments for Tapahtumatyyppi in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToTapahtumatyyppi(Tapahtumatyyppi tapahtumatyyppi)
        {
            base.AddObject("Tapahtumatyyppi", tapahtumatyyppi);
        }
    }
    /// <summary>
    /// There are no comments for HarkkaprojektiDBModel.Kayttaja in the schema.
    /// </summary>
    /// <KeyProperties>
    /// KayttajaId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HarkkaprojektiDBModel", Name="Kayttaja")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Kayttaja : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Kayttaja object.
        /// </summary>
        /// <param name="kayttajaId">Initial value of KayttajaId.</param>
        /// <param name="etunimi">Initial value of Etunimi.</param>
        /// <param name="sukunimi">Initial value of Sukunimi.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Kayttaja CreateKayttaja(int kayttajaId, string etunimi, string sukunimi)
        {
            Kayttaja kayttaja = new Kayttaja();
            kayttaja.KayttajaId = kayttajaId;
            kayttaja.Etunimi = etunimi;
            kayttaja.Sukunimi = sukunimi;
            return kayttaja;
        }
        /// <summary>
        /// There are no comments for property KayttajaId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int KayttajaId
        {
            get
            {
                return this._KayttajaId;
            }
            set
            {
                this.OnKayttajaIdChanging(value);
                this.ReportPropertyChanging("KayttajaId");
                this._KayttajaId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("KayttajaId");
                this.OnKayttajaIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _KayttajaId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnKayttajaIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnKayttajaIdChanged();
        /// <summary>
        /// There are no comments for property Etunimi in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Etunimi
        {
            get
            {
                return this._Etunimi;
            }
            set
            {
                this.OnEtunimiChanging(value);
                this.ReportPropertyChanging("Etunimi");
                this._Etunimi = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Etunimi");
                this.OnEtunimiChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Etunimi;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEtunimiChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEtunimiChanged();
        /// <summary>
        /// There are no comments for property Sukunimi in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Sukunimi
        {
            get
            {
                return this._Sukunimi;
            }
            set
            {
                this.OnSukunimiChanging(value);
                this.ReportPropertyChanging("Sukunimi");
                this._Sukunimi = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Sukunimi");
                this.OnSukunimiChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Sukunimi;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSukunimiChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSukunimiChanged();
        /// <summary>
        /// There are no comments for KayttajanTapahtumat in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HarkkaprojektiDBModel", "FK_KAYTTAJANTAPAHTUMAT_KAYTTAJAID", "KayttajanTapahtumat")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<KayttajanTapahtumat> KayttajanTapahtumat
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<KayttajanTapahtumat>("HarkkaprojektiDBModel.FK_KAYTTAJANTAPAHTUMAT_KAYTTAJAID", "KayttajanTapahtumat");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<KayttajanTapahtumat>("HarkkaprojektiDBModel.FK_KAYTTAJANTAPAHTUMAT_KAYTTAJAID", "KayttajanTapahtumat", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Ryhma in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HarkkaprojektiDBModel", "RyhmanJasenet", "Ryhma")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Ryhma> Ryhma
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Ryhma>("HarkkaprojektiDBModel.RyhmanJasenet", "Ryhma");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Ryhma>("HarkkaprojektiDBModel.RyhmanJasenet", "Ryhma", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for HarkkaprojektiDBModel.KayttajanTapahtumat in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TapahtumaId
    /// KayttajaId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HarkkaprojektiDBModel", Name="KayttajanTapahtumat")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class KayttajanTapahtumat : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new KayttajanTapahtumat object.
        /// </summary>
        /// <param name="tapahtumaId">Initial value of TapahtumaId.</param>
        /// <param name="kayttajaId">Initial value of KayttajaId.</param>
        /// <param name="rooli">Initial value of Rooli.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static KayttajanTapahtumat CreateKayttajanTapahtumat(int tapahtumaId, int kayttajaId, string rooli)
        {
            KayttajanTapahtumat kayttajanTapahtumat = new KayttajanTapahtumat();
            kayttajanTapahtumat.TapahtumaId = tapahtumaId;
            kayttajanTapahtumat.KayttajaId = kayttajaId;
            kayttajanTapahtumat.Rooli = rooli;
            return kayttajanTapahtumat;
        }
        /// <summary>
        /// There are no comments for property TapahtumaId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int TapahtumaId
        {
            get
            {
                return this._TapahtumaId;
            }
            set
            {
                this.OnTapahtumaIdChanging(value);
                this.ReportPropertyChanging("TapahtumaId");
                this._TapahtumaId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TapahtumaId");
                this.OnTapahtumaIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _TapahtumaId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTapahtumaIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTapahtumaIdChanged();
        /// <summary>
        /// There are no comments for property KayttajaId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int KayttajaId
        {
            get
            {
                return this._KayttajaId;
            }
            set
            {
                this.OnKayttajaIdChanging(value);
                this.ReportPropertyChanging("KayttajaId");
                this._KayttajaId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("KayttajaId");
                this.OnKayttajaIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _KayttajaId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnKayttajaIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnKayttajaIdChanged();
        /// <summary>
        /// There are no comments for property Rooli in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Rooli
        {
            get
            {
                return this._Rooli;
            }
            set
            {
                this.OnRooliChanging(value);
                this.ReportPropertyChanging("Rooli");
                this._Rooli = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Rooli");
                this.OnRooliChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Rooli;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRooliChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRooliChanged();
        /// <summary>
        /// There are no comments for Kayttaja in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HarkkaprojektiDBModel", "FK_KAYTTAJANTAPAHTUMAT_KAYTTAJAID", "Kayttaja")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Kayttaja Kayttaja
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Kayttaja>("HarkkaprojektiDBModel.FK_KAYTTAJANTAPAHTUMAT_KAYTTAJAID", "Kayttaja").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Kayttaja>("HarkkaprojektiDBModel.FK_KAYTTAJANTAPAHTUMAT_KAYTTAJAID", "Kayttaja").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Kayttaja in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Kayttaja> KayttajaReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Kayttaja>("HarkkaprojektiDBModel.FK_KAYTTAJANTAPAHTUMAT_KAYTTAJAID", "Kayttaja");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Kayttaja>("HarkkaprojektiDBModel.FK_KAYTTAJANTAPAHTUMAT_KAYTTAJAID", "Kayttaja", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Tapahtuma in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HarkkaprojektiDBModel", "FK_KAYTTAJANTAPAHTUMAT_TAPAHTUMAID", "Tapahtuma")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Tapahtuma Tapahtuma
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tapahtuma>("HarkkaprojektiDBModel.FK_KAYTTAJANTAPAHTUMAT_TAPAHTUMAID", "Tapahtuma").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tapahtuma>("HarkkaprojektiDBModel.FK_KAYTTAJANTAPAHTUMAT_TAPAHTUMAID", "Tapahtuma").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Tapahtuma in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Tapahtuma> TapahtumaReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tapahtuma>("HarkkaprojektiDBModel.FK_KAYTTAJANTAPAHTUMAT_TAPAHTUMAID", "Tapahtuma");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Tapahtuma>("HarkkaprojektiDBModel.FK_KAYTTAJANTAPAHTUMAT_TAPAHTUMAID", "Tapahtuma", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for HarkkaprojektiDBModel.Ryhma in the schema.
    /// </summary>
    /// <KeyProperties>
    /// RyhmaId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HarkkaprojektiDBModel", Name="Ryhma")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Ryhma : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Ryhma object.
        /// </summary>
        /// <param name="ryhmaId">Initial value of RyhmaId.</param>
        /// <param name="nimi">Initial value of Nimi.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Ryhma CreateRyhma(int ryhmaId, string nimi)
        {
            Ryhma ryhma = new Ryhma();
            ryhma.RyhmaId = ryhmaId;
            ryhma.Nimi = nimi;
            return ryhma;
        }
        /// <summary>
        /// There are no comments for property RyhmaId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int RyhmaId
        {
            get
            {
                return this._RyhmaId;
            }
            set
            {
                this.OnRyhmaIdChanging(value);
                this.ReportPropertyChanging("RyhmaId");
                this._RyhmaId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("RyhmaId");
                this.OnRyhmaIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _RyhmaId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRyhmaIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRyhmaIdChanged();
        /// <summary>
        /// There are no comments for property Nimi in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nimi
        {
            get
            {
                return this._Nimi;
            }
            set
            {
                this.OnNimiChanging(value);
                this.ReportPropertyChanging("Nimi");
                this._Nimi = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Nimi");
                this.OnNimiChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nimi;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNimiChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNimiChanged();
        /// <summary>
        /// There are no comments for Kayttaja in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HarkkaprojektiDBModel", "RyhmanJasenet", "Kayttaja")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Kayttaja> Kayttaja
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Kayttaja>("HarkkaprojektiDBModel.RyhmanJasenet", "Kayttaja");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Kayttaja>("HarkkaprojektiDBModel.RyhmanJasenet", "Kayttaja", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for HarkkaprojektiDBModel.Tapahtuma in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TapahtumaId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HarkkaprojektiDBModel", Name="Tapahtuma")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Tapahtuma : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Tapahtuma object.
        /// </summary>
        /// <param name="tapahtumaId">Initial value of TapahtumaId.</param>
        /// <param name="alkamisAika">Initial value of AlkamisAika.</param>
        /// <param name="paattymisAika">Initial value of PaattymisAika.</param>
        /// <param name="nimi">Initial value of Nimi.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Tapahtuma CreateTapahtuma(int tapahtumaId, global::System.DateTime alkamisAika, global::System.DateTime paattymisAika, string nimi)
        {
            Tapahtuma tapahtuma = new Tapahtuma();
            tapahtuma.TapahtumaId = tapahtumaId;
            tapahtuma.AlkamisAika = alkamisAika;
            tapahtuma.PaattymisAika = paattymisAika;
            tapahtuma.Nimi = nimi;
            return tapahtuma;
        }
        /// <summary>
        /// There are no comments for property TapahtumaId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int TapahtumaId
        {
            get
            {
                return this._TapahtumaId;
            }
            set
            {
                this.OnTapahtumaIdChanging(value);
                this.ReportPropertyChanging("TapahtumaId");
                this._TapahtumaId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TapahtumaId");
                this.OnTapahtumaIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _TapahtumaId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTapahtumaIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTapahtumaIdChanged();
        /// <summary>
        /// There are no comments for property AlkamisAika in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime AlkamisAika
        {
            get
            {
                return this._AlkamisAika;
            }
            set
            {
                this.OnAlkamisAikaChanging(value);
                this.ReportPropertyChanging("AlkamisAika");
                this._AlkamisAika = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AlkamisAika");
                this.OnAlkamisAikaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _AlkamisAika;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAlkamisAikaChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAlkamisAikaChanged();
        /// <summary>
        /// There are no comments for property PaattymisAika in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime PaattymisAika
        {
            get
            {
                return this._PaattymisAika;
            }
            set
            {
                this.OnPaattymisAikaChanging(value);
                this.ReportPropertyChanging("PaattymisAika");
                this._PaattymisAika = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PaattymisAika");
                this.OnPaattymisAikaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _PaattymisAika;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPaattymisAikaChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPaattymisAikaChanged();
        /// <summary>
        /// There are no comments for property Paikka in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Paikka
        {
            get
            {
                return this._Paikka;
            }
            set
            {
                this.OnPaikkaChanging(value);
                this.ReportPropertyChanging("Paikka");
                this._Paikka = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Paikka");
                this.OnPaikkaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Paikka;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPaikkaChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPaikkaChanged();
        /// <summary>
        /// There are no comments for property Nimi in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nimi
        {
            get
            {
                return this._Nimi;
            }
            set
            {
                this.OnNimiChanging(value);
                this.ReportPropertyChanging("Nimi");
                this._Nimi = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Nimi");
                this.OnNimiChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nimi;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNimiChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNimiChanged();
        /// <summary>
        /// There are no comments for KayttajanTapahtumat in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HarkkaprojektiDBModel", "FK_KAYTTAJANTAPAHTUMAT_TAPAHTUMAID", "KayttajanTapahtumat")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<KayttajanTapahtumat> KayttajanTapahtumat
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<KayttajanTapahtumat>("HarkkaprojektiDBModel.FK_KAYTTAJANTAPAHTUMAT_TAPAHTUMAID", "KayttajanTapahtumat");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<KayttajanTapahtumat>("HarkkaprojektiDBModel.FK_KAYTTAJANTAPAHTUMAT_TAPAHTUMAID", "KayttajanTapahtumat", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Tapahtumatyyppi in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HarkkaprojektiDBModel", "FK_TAPAHTUMA_TYYPPIID", "Tapahtumatyyppi")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Tapahtumatyyppi Tapahtumatyyppi
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tapahtumatyyppi>("HarkkaprojektiDBModel.FK_TAPAHTUMA_TYYPPIID", "Tapahtumatyyppi").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tapahtumatyyppi>("HarkkaprojektiDBModel.FK_TAPAHTUMA_TYYPPIID", "Tapahtumatyyppi").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Tapahtumatyyppi in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Tapahtumatyyppi> TapahtumatyyppiReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tapahtumatyyppi>("HarkkaprojektiDBModel.FK_TAPAHTUMA_TYYPPIID", "Tapahtumatyyppi");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Tapahtumatyyppi>("HarkkaprojektiDBModel.FK_TAPAHTUMA_TYYPPIID", "Tapahtumatyyppi", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for HarkkaprojektiDBModel.Tapahtumatyyppi in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TyyppiId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HarkkaprojektiDBModel", Name="Tapahtumatyyppi")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Tapahtumatyyppi : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Tapahtumatyyppi object.
        /// </summary>
        /// <param name="tyyppiId">Initial value of TyyppiId.</param>
        /// <param name="nimi">Initial value of Nimi.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Tapahtumatyyppi CreateTapahtumatyyppi(int tyyppiId, string nimi)
        {
            Tapahtumatyyppi tapahtumatyyppi = new Tapahtumatyyppi();
            tapahtumatyyppi.TyyppiId = tyyppiId;
            tapahtumatyyppi.Nimi = nimi;
            return tapahtumatyyppi;
        }
        /// <summary>
        /// There are no comments for property TyyppiId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int TyyppiId
        {
            get
            {
                return this._TyyppiId;
            }
            set
            {
                this.OnTyyppiIdChanging(value);
                this.ReportPropertyChanging("TyyppiId");
                this._TyyppiId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TyyppiId");
                this.OnTyyppiIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _TyyppiId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTyyppiIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTyyppiIdChanged();
        /// <summary>
        /// There are no comments for property Nimi in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nimi
        {
            get
            {
                return this._Nimi;
            }
            set
            {
                this.OnNimiChanging(value);
                this.ReportPropertyChanging("Nimi");
                this._Nimi = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Nimi");
                this.OnNimiChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nimi;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNimiChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNimiChanged();
        /// <summary>
        /// There are no comments for Tapahtuma in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("HarkkaprojektiDBModel", "FK_TAPAHTUMA_TYYPPIID", "Tapahtuma")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Tapahtuma> Tapahtuma
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Tapahtuma>("HarkkaprojektiDBModel.FK_TAPAHTUMA_TYYPPIID", "Tapahtuma");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Tapahtuma>("HarkkaprojektiDBModel.FK_TAPAHTUMA_TYYPPIID", "Tapahtuma", value);
                }
            }
        }
    }
}
