USE [master]
GO

/****** Object:  Database [HarkkaprojektiDB]    Script Date: 05/14/2014 14:54:17 ******/
CREATE DATABASE [HarkkaprojektiDB] ON  PRIMARY 
( NAME = N'HarkkaprojektiDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\HarkkaprojektiDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HarkkaprojektiDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\HarkkaprojektiDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HarkkaprojektiDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HarkkaprojektiDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HarkkaprojektiDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [HarkkaprojektiDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HarkkaprojektiDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HarkkaprojektiDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HarkkaprojektiDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HarkkaprojektiDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET  READ_WRITE 
GO

ALTER DATABASE [HarkkaprojektiDB] SET RECOVERY FULL 
GO

ALTER DATABASE [HarkkaprojektiDB] SET  MULTI_USER 
GO

ALTER DATABASE [HarkkaprojektiDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HarkkaprojektiDB] SET DB_CHAINING OFF 
GO

USE [HarkkaprojektiDB]
GO

/****** Object:  Table [dbo].[User]    Script Date: 05/14/2014 14:57:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[User](
	[UserID] [uniqueidentifier] NOT NULL,
	[UserName] [varchar](255) NOT NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [HarkkaprojektiDB]
GO

/****** Object:  Table [dbo].[Group]    Script Date: 05/14/2014 14:57:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Group](
	[GroupId] [uniqueidentifier] NOT NULL,
	[Name] [varchar](255) NOT NULL,
 CONSTRAINT [PK_GROUP] PRIMARY KEY CLUSTERED 
(
	[GroupId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [HarkkaprojektiDB]
GO

/****** Object:  Table [dbo].[GroupMembers]    Script Date: 05/14/2014 14:58:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GroupMembers](
	[UserId] [uniqueidentifier] NOT NULL,
	[GroupId] [uniqueidentifier] NOT NULL,
	[Role] [varchar](50) NULL,
 CONSTRAINT [PK_GROUPMEMBERS] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[GroupId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[GroupMembers]  WITH CHECK ADD  CONSTRAINT [FK_GROUPMEMBERS_GROUPID] FOREIGN KEY([GroupId])
REFERENCES [dbo].[Group] ([GroupId])
GO

ALTER TABLE [dbo].[GroupMembers] CHECK CONSTRAINT [FK_GROUPMEMBERS_GROUPID]
GO

ALTER TABLE [dbo].[GroupMembers]  WITH CHECK ADD  CONSTRAINT [FK_GROUPMEMBERS_USERID] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([UserID])
GO

ALTER TABLE [dbo].[GroupMembers] CHECK CONSTRAINT [FK_GROUPMEMBERS_USERID]
GO

USE [HarkkaprojektiDB]
GO

/****** Object:  Table [dbo].[EventType]    Script Date: 05/14/2014 14:58:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EventType](
	[TypeId] [int] NOT NULL,
	[Name] [varchar](255) NOT NULL,
 CONSTRAINT [PK_EVENTTYPE] PRIMARY KEY CLUSTERED 
(
	[TypeId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [HarkkaprojektiDB]
GO

/****** Object:  Table [dbo].[Event]    Script Date: 05/14/2014 14:58:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Event](
	[EventId] [uniqueidentifier] NOT NULL,
	[TypeId] [int] NOT NULL,
	[Name] [varchar](255) NOT NULL,
	[Summary] [varchar](255) NULL,
	[Location] [varchar](255) NULL,
	[StartTime] [datetime] NOT NULL,
	[EndTime] [datetime] NOT NULL,
 CONSTRAINT [PK_EVENT] PRIMARY KEY CLUSTERED 
(
	[EventId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Event]  WITH CHECK ADD  CONSTRAINT [FK_EVENT_TYPEID] FOREIGN KEY([TypeId])
REFERENCES [dbo].[EventType] ([TypeId])
GO

ALTER TABLE [dbo].[Event] CHECK CONSTRAINT [FK_EVENT_TYPEID]
GO

USE [HarkkaprojektiDB]
GO

/****** Object:  Table [dbo].[AttendeeStatus]    Script Date: 05/14/2014 14:59:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AttendeeStatus](
	[StatusId] [int] NOT NULL,
	[Name] [varchar](255) NOT NULL,
 CONSTRAINT [PK_ATTENDEESTATUS] PRIMARY KEY CLUSTERED 
(
	[StatusId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [HarkkaprojektiDB]
GO

/****** Object:  Table [dbo].[Attendees]    Script Date: 05/14/2014 14:59:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Attendees](
	[UserId] [uniqueidentifier] NOT NULL,
	[EventId] [uniqueidentifier] NOT NULL,
	[AttendeeStatusId] [int] NOT NULL,
 CONSTRAINT [PK_ATTENDEES] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[EventId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Attendees]  WITH CHECK ADD  CONSTRAINT [FK_ATTENDEES_ATTENDEESTATUSID] FOREIGN KEY([AttendeeStatusId])
REFERENCES [dbo].[AttendeeStatus] ([StatusId])
GO

ALTER TABLE [dbo].[Attendees] CHECK CONSTRAINT [FK_ATTENDEES_ATTENDEESTATUSID]
GO

ALTER TABLE [dbo].[Attendees]  WITH CHECK ADD  CONSTRAINT [FK_ATTENDEES_EVENTID] FOREIGN KEY([EventId])
REFERENCES [dbo].[Event] ([EventId])
GO

ALTER TABLE [dbo].[Attendees] CHECK CONSTRAINT [FK_ATTENDEES_EVENTID]
GO

ALTER TABLE [dbo].[Attendees]  WITH CHECK ADD  CONSTRAINT [FK_ATTENDEES_USERID] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([UserID])
GO

ALTER TABLE [dbo].[Attendees] CHECK CONSTRAINT [FK_ATTENDEES_USERID]
GO

