//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDB_Service")]
    public interface IDB_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDB_Service/FetchEventByGuid", ReplyAction="http://tempuri.org/IDB_Service/FetchEventByGuidResponse")]
        Service_Solution.DTO_Models.UpcomingEventDTO FetchEventByGuid(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDB_Service/FetchEventByGuid", ReplyAction="http://tempuri.org/IDB_Service/FetchEventByGuidResponse")]
        System.Threading.Tasks.Task<Service_Solution.DTO_Models.UpcomingEventDTO> FetchEventByGuidAsync(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDB_Service/FetchUpcomingEvents", ReplyAction="http://tempuri.org/IDB_Service/FetchUpcomingEventsResponse")]
        Service_Solution.DTO_Models.UpcomingEventDTO[] FetchUpcomingEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDB_Service/FetchUpcomingEvents", ReplyAction="http://tempuri.org/IDB_Service/FetchUpcomingEventsResponse")]
        System.Threading.Tasks.Task<Service_Solution.DTO_Models.UpcomingEventDTO[]> FetchUpcomingEventsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDB_Service/FetchUpcomingEventsShort", ReplyAction="http://tempuri.org/IDB_Service/FetchUpcomingEventsShortResponse")]
        Service_Solution.DTO_Models.UpcomingEventShortDTO[] FetchUpcomingEventsShort();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDB_Service/FetchUpcomingEventsShort", ReplyAction="http://tempuri.org/IDB_Service/FetchUpcomingEventsShortResponse")]
        System.Threading.Tasks.Task<Service_Solution.DTO_Models.UpcomingEventShortDTO[]> FetchUpcomingEventsShortAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDB_ServiceChannel : ConsoleTest.ServiceReference1.IDB_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DB_ServiceClient : System.ServiceModel.ClientBase<ConsoleTest.ServiceReference1.IDB_Service>, ConsoleTest.ServiceReference1.IDB_Service {
        
        public DB_ServiceClient() {
        }
        
        public DB_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DB_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DB_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DB_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Service_Solution.DTO_Models.UpcomingEventDTO FetchEventByGuid(System.Guid guid) {
            return base.Channel.FetchEventByGuid(guid);
        }
        
        public System.Threading.Tasks.Task<Service_Solution.DTO_Models.UpcomingEventDTO> FetchEventByGuidAsync(System.Guid guid) {
            return base.Channel.FetchEventByGuidAsync(guid);
        }
        
        public Service_Solution.DTO_Models.UpcomingEventDTO[] FetchUpcomingEvents() {
            return base.Channel.FetchUpcomingEvents();
        }
        
        public System.Threading.Tasks.Task<Service_Solution.DTO_Models.UpcomingEventDTO[]> FetchUpcomingEventsAsync() {
            return base.Channel.FetchUpcomingEventsAsync();
        }
        
        public Service_Solution.DTO_Models.UpcomingEventShortDTO[] FetchUpcomingEventsShort() {
            return base.Channel.FetchUpcomingEventsShort();
        }
        
        public System.Threading.Tasks.Task<Service_Solution.DTO_Models.UpcomingEventShortDTO[]> FetchUpcomingEventsShortAsync() {
            return base.Channel.FetchUpcomingEventsShortAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IClientAccessPolicy")]
    public interface IClientAccessPolicy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientAccessPolicy/GetClientAccessPolicy", ReplyAction="http://tempuri.org/IClientAccessPolicy/GetClientAccessPolicyResponse")]
        System.IO.Stream GetClientAccessPolicy();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientAccessPolicy/GetClientAccessPolicy", ReplyAction="http://tempuri.org/IClientAccessPolicy/GetClientAccessPolicyResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetClientAccessPolicyAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientAccessPolicyChannel : ConsoleTest.ServiceReference1.IClientAccessPolicy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientAccessPolicyClient : System.ServiceModel.ClientBase<ConsoleTest.ServiceReference1.IClientAccessPolicy>, ConsoleTest.ServiceReference1.IClientAccessPolicy {
        
        public ClientAccessPolicyClient() {
        }
        
        public ClientAccessPolicyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientAccessPolicyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientAccessPolicyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientAccessPolicyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream GetClientAccessPolicy() {
            return base.Channel.GetClientAccessPolicy();
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetClientAccessPolicyAsync() {
            return base.Channel.GetClientAccessPolicyAsync();
        }
    }
}
