//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Kalenteri_DBEntities : DbContext
    {
        public Kalenteri_DBEntities()
            : base("name=Kalenteri_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Kayttaja> Kayttaja { get; set; }
        public DbSet<KayttajanTapahtumat> KayttajanTapahtumat { get; set; }
        public DbSet<Ryhma> Ryhma { get; set; }
        public DbSet<RyhmanJasenet> RyhmanJasenet { get; set; }
        public DbSet<Tapahtuma> Tapahtuma { get; set; }
        public DbSet<Tapahtumatyyppi> Tapahtumatyyppi { get; set; }
    }
}
