//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public partial class Kayttaja
    {
        public Kayttaja()
        {
            this.KayttajanTapahtumat = new List<KayttajanTapahtumat>();
            this.RyhmanJasenet = new List<RyhmanJasenet>();
        }
    
        [DataMember]
        public int KayttajaId { get; set; }
        [DataMember]
        public string Etunimi { get; set; }
        [DataMember]
        public string Sukunimi { get; set; }
    
        public virtual ICollection<KayttajanTapahtumat> KayttajanTapahtumat { get; set; }
        public virtual ICollection<RyhmanJasenet> RyhmanJasenet { get; set; }
    }
}
