//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ryhma
    {
        public Ryhma()
        {
            this.RyhmanJasenet = new HashSet<RyhmanJasenet>();
        }
    
        public int RyhmaId { get; set; }
        public string Nimi { get; set; }
    
        public virtual ICollection<RyhmanJasenet> RyhmanJasenet { get; set; }
    }
}
