//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RyhmanJasenet
    {
        public int KayttajaId { get; set; }
        public int RyhmaId { get; set; }
        public string KROOLI { get; set; }
    
        public virtual Kayttaja Kayttaja { get; set; }
        public virtual Ryhma Ryhma { get; set; }
    }
}
