//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tapahtumatyyppi
    {
        public Tapahtumatyyppi()
        {
            this.Tapahtuma = new HashSet<Tapahtuma>();
        }
    
        public int TyyppiId { get; set; }
        public string Nimi { get; set; }
    
        public virtual ICollection<Tapahtuma> Tapahtuma { get; set; }
    }
}
