//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tapahtuma
    {
        public Tapahtuma()
        {
            this.KayttajanTapahtumat = new HashSet<KayttajanTapahtumat>();
        }
    
        public int TapahtumaId { get; set; }
        public int TyyppiId { get; set; }
        public System.DateTime AlkamisAika { get; set; }
        public System.DateTime PaattymisAika { get; set; }
        public string Paikka { get; set; }
        public string Nimi { get; set; }
    
        public virtual ICollection<KayttajanTapahtumat> KayttajanTapahtumat { get; set; }
        public virtual Tapahtumatyyppi Tapahtumatyyppi { get; set; }
    }
}
