//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Harkkaprojekti.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/HaeKayttajanNimi", ReplyAction="http://tempuri.org/IService1/HaeKayttajanNimiResponse")]
        System.IAsyncResult BeginHaeKayttajanNimi(int id, System.AsyncCallback callback, object asyncState);
        
        string EndHaeKayttajanNimi(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/haeKaikkienKayttajienNimet", ReplyAction="http://tempuri.org/IService1/haeKaikkienKayttajienNimetResponse")]
        System.IAsyncResult BeginhaeKaikkienKayttajienNimet(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndhaeKaikkienKayttajienNimet(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Harkkaprojekti.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HaeKayttajanNimiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HaeKayttajanNimiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class haeKaikkienKayttajienNimetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public haeKaikkienKayttajienNimetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Harkkaprojekti.ServiceReference1.IService1>, Harkkaprojekti.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginHaeKayttajanNimiDelegate;
        
        private EndOperationDelegate onEndHaeKayttajanNimiDelegate;
        
        private System.Threading.SendOrPostCallback onHaeKayttajanNimiCompletedDelegate;
        
        private BeginOperationDelegate onBeginhaeKaikkienKayttajienNimetDelegate;
        
        private EndOperationDelegate onEndhaeKaikkienKayttajienNimetDelegate;
        
        private System.Threading.SendOrPostCallback onhaeKaikkienKayttajienNimetCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<HaeKayttajanNimiCompletedEventArgs> HaeKayttajanNimiCompleted;
        
        public event System.EventHandler<haeKaikkienKayttajienNimetCompletedEventArgs> haeKaikkienKayttajienNimetCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Harkkaprojekti.ServiceReference1.IService1.BeginHaeKayttajanNimi(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHaeKayttajanNimi(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string Harkkaprojekti.ServiceReference1.IService1.EndHaeKayttajanNimi(System.IAsyncResult result) {
            return base.Channel.EndHaeKayttajanNimi(result);
        }
        
        private System.IAsyncResult OnBeginHaeKayttajanNimi(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return ((Harkkaprojekti.ServiceReference1.IService1)(this)).BeginHaeKayttajanNimi(id, callback, asyncState);
        }
        
        private object[] OnEndHaeKayttajanNimi(System.IAsyncResult result) {
            string retVal = ((Harkkaprojekti.ServiceReference1.IService1)(this)).EndHaeKayttajanNimi(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHaeKayttajanNimiCompleted(object state) {
            if ((this.HaeKayttajanNimiCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HaeKayttajanNimiCompleted(this, new HaeKayttajanNimiCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HaeKayttajanNimiAsync(int id) {
            this.HaeKayttajanNimiAsync(id, null);
        }
        
        public void HaeKayttajanNimiAsync(int id, object userState) {
            if ((this.onBeginHaeKayttajanNimiDelegate == null)) {
                this.onBeginHaeKayttajanNimiDelegate = new BeginOperationDelegate(this.OnBeginHaeKayttajanNimi);
            }
            if ((this.onEndHaeKayttajanNimiDelegate == null)) {
                this.onEndHaeKayttajanNimiDelegate = new EndOperationDelegate(this.OnEndHaeKayttajanNimi);
            }
            if ((this.onHaeKayttajanNimiCompletedDelegate == null)) {
                this.onHaeKayttajanNimiCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHaeKayttajanNimiCompleted);
            }
            base.InvokeAsync(this.onBeginHaeKayttajanNimiDelegate, new object[] {
                        id}, this.onEndHaeKayttajanNimiDelegate, this.onHaeKayttajanNimiCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Harkkaprojekti.ServiceReference1.IService1.BeginhaeKaikkienKayttajienNimet(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginhaeKaikkienKayttajienNimet(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> Harkkaprojekti.ServiceReference1.IService1.EndhaeKaikkienKayttajienNimet(System.IAsyncResult result) {
            return base.Channel.EndhaeKaikkienKayttajienNimet(result);
        }
        
        private System.IAsyncResult OnBeginhaeKaikkienKayttajienNimet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Harkkaprojekti.ServiceReference1.IService1)(this)).BeginhaeKaikkienKayttajienNimet(callback, asyncState);
        }
        
        private object[] OnEndhaeKaikkienKayttajienNimet(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((Harkkaprojekti.ServiceReference1.IService1)(this)).EndhaeKaikkienKayttajienNimet(result);
            return new object[] {
                    retVal};
        }
        
        private void OnhaeKaikkienKayttajienNimetCompleted(object state) {
            if ((this.haeKaikkienKayttajienNimetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.haeKaikkienKayttajienNimetCompleted(this, new haeKaikkienKayttajienNimetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void haeKaikkienKayttajienNimetAsync() {
            this.haeKaikkienKayttajienNimetAsync(null);
        }
        
        public void haeKaikkienKayttajienNimetAsync(object userState) {
            if ((this.onBeginhaeKaikkienKayttajienNimetDelegate == null)) {
                this.onBeginhaeKaikkienKayttajienNimetDelegate = new BeginOperationDelegate(this.OnBeginhaeKaikkienKayttajienNimet);
            }
            if ((this.onEndhaeKaikkienKayttajienNimetDelegate == null)) {
                this.onEndhaeKaikkienKayttajienNimetDelegate = new EndOperationDelegate(this.OnEndhaeKaikkienKayttajienNimet);
            }
            if ((this.onhaeKaikkienKayttajienNimetCompletedDelegate == null)) {
                this.onhaeKaikkienKayttajienNimetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnhaeKaikkienKayttajienNimetCompleted);
            }
            base.InvokeAsync(this.onBeginhaeKaikkienKayttajienNimetDelegate, null, this.onEndhaeKaikkienKayttajienNimetDelegate, this.onhaeKaikkienKayttajienNimetCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Harkkaprojekti.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<Harkkaprojekti.ServiceReference1.IService1>, Harkkaprojekti.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<Harkkaprojekti.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginHaeKayttajanNimi(int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("HaeKayttajanNimi", _args, callback, asyncState);
                return _result;
            }
            
            public string EndHaeKayttajanNimi(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("HaeKayttajanNimi", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginhaeKaikkienKayttajienNimet(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("haeKaikkienKayttajienNimet", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndhaeKaikkienKayttajienNimet(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("haeKaikkienKayttajienNimet", _args, result)));
                return _result;
            }
        }
    }
}
