USE [master]
GO

/****** Object:  Database [HarkkaprojektiDB]    Script Date: 05/14/2014 14:54:17 ******/
CREATE DATABASE [HarkkaprojektiDB] ON  PRIMARY 
( NAME = N'HarkkaprojektiDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\HarkkaprojektiDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HarkkaprojektiDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\HarkkaprojektiDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HarkkaprojektiDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HarkkaprojektiDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HarkkaprojektiDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [HarkkaprojektiDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HarkkaprojektiDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HarkkaprojektiDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HarkkaprojektiDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HarkkaprojektiDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HarkkaprojektiDB] SET  READ_WRITE 
GO

ALTER DATABASE [HarkkaprojektiDB] SET RECOVERY FULL 
GO

ALTER DATABASE [HarkkaprojektiDB] SET  MULTI_USER 
GO

ALTER DATABASE [HarkkaprojektiDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HarkkaprojektiDB] SET DB_CHAINING OFF 
GO

