USE [HarkkaprojektiDB]
GO

/****** Object:  Table [dbo].[GroupMembers]    Script Date: 05/14/2014 14:58:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[GroupMembers](
	[UserId] [uniqueidentifier] NOT NULL,
	[GroupId] [uniqueidentifier] NOT NULL,
	[Role] [varchar](50) NULL,
 CONSTRAINT [PK_GROUPMEMBERS] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[GroupId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[GroupMembers]  WITH CHECK ADD  CONSTRAINT [FK_GROUPMEMBERS_GROUPID] FOREIGN KEY([GroupId])
REFERENCES [dbo].[Group] ([GroupId])
GO

ALTER TABLE [dbo].[GroupMembers] CHECK CONSTRAINT [FK_GROUPMEMBERS_GROUPID]
GO

ALTER TABLE [dbo].[GroupMembers]  WITH CHECK ADD  CONSTRAINT [FK_GROUPMEMBERS_USERID] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([UserID])
GO

ALTER TABLE [dbo].[GroupMembers] CHECK CONSTRAINT [FK_GROUPMEMBERS_USERID]
GO

