USE [HarkkaprojektiDB]
GO

/****** Object:  Table [dbo].[Attendees]    Script Date: 05/14/2014 14:59:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Attendees](
	[UserId] [uniqueidentifier] NOT NULL,
	[EventId] [uniqueidentifier] NOT NULL,
	[AttendeeStatusId] [int] NOT NULL,
 CONSTRAINT [PK_ATTENDEES] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[EventId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Attendees]  WITH CHECK ADD  CONSTRAINT [FK_ATTENDEES_ATTENDEESTATUSID] FOREIGN KEY([AttendeeStatusId])
REFERENCES [dbo].[AttendeeStatus] ([StatusId])
GO

ALTER TABLE [dbo].[Attendees] CHECK CONSTRAINT [FK_ATTENDEES_ATTENDEESTATUSID]
GO

ALTER TABLE [dbo].[Attendees]  WITH CHECK ADD  CONSTRAINT [FK_ATTENDEES_EVENTID] FOREIGN KEY([EventId])
REFERENCES [dbo].[Event] ([EventId])
GO

ALTER TABLE [dbo].[Attendees] CHECK CONSTRAINT [FK_ATTENDEES_EVENTID]
GO

ALTER TABLE [dbo].[Attendees]  WITH CHECK ADD  CONSTRAINT [FK_ATTENDEES_USERID] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([UserID])
GO

ALTER TABLE [dbo].[Attendees] CHECK CONSTRAINT [FK_ATTENDEES_USERID]
GO

